name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o git-context-switcher-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o git-context-switcher-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o git-context-switcher-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o git-context-switcher-windows-amd64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            git-context-switcher-linux-amd64
            git-context-switcher-darwin-amd64
            git-context-switcher-darwin-arm64
            git-context-switcher-windows-amd64.exe
          generate_release_notes: true
